### ISSUE TITLE
5장 1. 누락 데이터 처리 ~ 3. 데이터 표준화 진행

### ISSUE THREAD

**Issue by ppiazi** [bbongcat/Data-Science-Newbie#5]

**Comment by bbongcat** [comment]
제가 나눠서 하기로 한걸 깜빡하고 5장을 다 해버렸습니다.. ^^;;
데이터 표준화 이후의 내용은 레파지토리에서 삭제할까요?

**Comment by ppiazi** [comment]
해버렸으면 ㅎㅎ 그대로 올립시다.
수고했습니다. close 합니다.
